export const quizInstructionsMap = {
  "1756821640950": {
    "name": "HappiLife",
    "start_instructions": "",
    "report_header": "# **Mental Wellness**\n\nMental Wellness constitutes of:\n\n- **Behavioural Health:** How we behave  \n- **Cognitive Health:** How we think  \n- **Emotional Health:** How we feel  \n- **Quality of Life:** Facets of physical health, social relations, spirituality, etc.  \n\n---\n\n## **Summary Overview**\n\nThe summary provides you with a **snapshot of your mental wellbeing, virtues, and vices**.  \n\nThe first step towards emotional wellness is **awareness of your capacities** — the beginning point of your wellness journey.  \n\nThis summary:  \n- Compiles your strengths, opportunities, and various facets of your personality  \n- Scales your emotional wellness across **10 parameters** based on your screening responses  \n- Acts as a **mirror**, describing and guiding you towards holistic wellness  \n\n---\n\n## **Next Step**\n\nYou can also opt for an **assisted summary reading** with a qualified mental wellness expert to gain deeper insights and actionable steps.  \n\n---\n\n## **Disclaimer**\n\n⚠️ The summary is **indicative** and **not equivalent to medical advice**.\n"
  },
  "1758167047093": {
    "name": "HappiEQ",
    "start_instructions": "",
    "report_header": "# HappiEQ Self Assessment\n\n## About this Summary\n\nEmotional Intelligence (measured as Emotional Quotient – EQ) is at the heart of how we understand ourselves and relate to others. It influences the way we manage emotional balance, communicate, make decisions and build meaningful relationships.\n\nThis summary provides you with a snapshot of your EQ profile across key dimensions—**self-image, emotional-regulation, self drive, understanding others, and interpersonal effectiveness.**\n\nThe purpose of this report is to highlight your emotional strengths and growth areas, giving you a clearer picture of how your emotional intelligence shows up in daily life. By becoming aware of these patterns, you take the first step towards enhancing your personal effectiveness, building stronger connections, and thriving both personally and professionally.\n"
  },
  "1765417314557": {
    "name": "Personality",
    "start_instructions": "",
    "report_header": "**Summary:** This report presents the personality profile derived from your quiz responses, including dominant traits, growth suggestions, and recommended next steps."
  },
  "1774259823760": {
    "name": "Sleep Quality",
    "start_instructions": "Waking up feeling truly refreshed gives you a significant advantage, providing the mental clarity, emotional stability, and physical energy needed to excel in everything you do. This consistent harmony is a powerful testament to your self-discipline and your commitment to long-term health and happiness!",
    "report_header": "Waking up feeling truly refreshed gives you a significant advantage, providing the mental clarity, emotional stability, and physical energy needed to excel in everything you do. This consistent harmony is a powerful testament to your self-discipline and your commitment to long-term health and happiness!"
  },
  "1774418876289": {
    "name": "Anger Management",
    "start_instructions": "Anger is a natural, powerful emotion that typically arises in response to perceived threats, injustice, or frustration. While it is a normal human experience, anger management is the process of recognizing your triggers and learning to express that energy in a constructive, rather than destructive, manner.\n\nWhen anger is left unmanaged, it can deeply impact your life, straining relationships, hindering professional growth, and causing physical stress like high blood pressure. Conversely, mastering your response allows you to communicate needs clearly and maintain control during conflict. This assessment is designed to help you understand your current patterns and emotional triggers. Please answer honestly; there are no wrong answers. This is a vital first step toward transforming your anger into a tool for positive change and reclaiming your inner peace.",
    "report_header": "Anger is a natural, powerful emotion that typically arises in response to perceived threats, injustice, or frustration. While it is a normal human experience, anger management is the process of recognizing your triggers and learning to express that energy in a constructive, rather than destructive, manner.\n\nWhen anger is left unmanaged, it can deeply impact your life, straining relationships, hindering professional growth, and causing physical stress like high blood pressure. Conversely, mastering your response allows you to communicate needs clearly and maintain control during conflict. This assessment is designed to help you understand your current patterns and emotional triggers. Please answer honestly; there are no wrong answers. This is a vital first step toward transforming your anger into a tool for positive change and reclaiming your inner peace."
  },
  "1774418925096": {
    "name": "Bullying",
    "start_instructions": "Bullying is the repetitive, intentional abuse of power aimed at causing physical or emotional distress. It is identified by a pattern of behavior rather than a one-time conflict that includes physical aggression, verbal insults, social exclusion, or digital harassment. Because it relies on an imbalance of power, victims often feel unable to stop the interaction on their own.\n\nThe harm caused by bullying is significant, often leading to chronic anxiety, depression, and a loss of self-esteem that can persist for years. It doesn't just affect the individual; it creates an environment of fear and mistrust for everyone.\n\nThis assessment is designed to help you identify these harmful patterns and bring them to light. Please answer honestly, knowing there are no wrong answers. Recognizing the situation is the first courageous step toward reclaiming your safety and well-being.",
    "report_header": "Bullying is the repetitive, intentional abuse of power aimed at causing physical or emotional distress. It is identified by a pattern of behavior rather than a one-time conflict that includes physical aggression, verbal insults, social exclusion, or digital harassment. Because it relies on an imbalance of power, victims often feel unable to stop the interaction on their own.\n\nThe harm caused by bullying is significant, often leading to chronic anxiety, depression, and a loss of self-esteem that can persist for years. It doesn't just affect the individual; it creates an environment of fear and mistrust for everyone.\n\nThis assessment is designed to help you identify these harmful patterns and bring them to light. Please answer honestly, knowing there are no wrong answers. Recognizing the situation is the first courageous step toward reclaiming your safety and well-being."
  },
  "1774418998963": {
    "name": "Postnatal Postpartum",
    "start_instructions": "Preparing for the arrival of a new family member is a profound journey that encompasses significant physical, emotional, and lifestyle transitions. This assessment is designed to help you check in with yourself and gain a clear understanding of your current mental well-being during this important time. Please approach each question with honesty, knowing that there are no right or wrong answers - only a path toward ensuring you feel supported, balanced, and ready for the road ahead.",
    "report_header": "Preparing for the arrival of a new family member is a profound journey that encompasses significant physical, emotional, and lifestyle transitions. This assessment is designed to help you check in with yourself and gain a clear understanding of your current mental well-being during this important time. Please approach each question with honesty, knowing that there are no right or wrong answers - only a path toward ensuring you feel supported, balanced, and ready for the road ahead."
  },
  "1774419022110": {
    "name": "Stress Management",
    "start_instructions": "Stress is your body’s internal alarm system. In small doses, it’s a superpower that sharpens your focus and helps you crush a deadline or run a race. But when the alarm won't turn off, it becomes a heavy weight that drains your energy, affects your health, and clouds your joy.\n\nThe secret? It’s all about balance. This assessment is your personal guide to understanding your stress levels and learning how to make that energy work for you, not against you.",
    "report_header": "Stress is your body’s internal alarm system. In small doses, it’s a superpower that sharpens your focus and helps you crush a deadline or run a race. But when the alarm won't turn off, it becomes a heavy weight that drains your energy, affects your health, and clouds your joy.\n\nThe secret? It’s all about balance. This assessment is your personal guide to understanding your stress levels and learning how to make that energy work for you, not against you."
  },
  "1774419049936": {
    "name": "Worry",
    "start_instructions": "Worry is like a background app running on your phone it quietly drains your battery, slows your focus, and keeps you from enjoying the moment. It’s that what-if loop that turns small pebbles into mountains, affecting everything from your sleep to your confidence.\n\nThe good news? You can hit the refresh button. This assessment is designed to help you spot those mental loops and trade restless thoughts for total clarity. It’s not just a test; it’s your personal toolkit for a lighter, calmer mind.\n\nReady to silence the noise and reclaim your energy? Let’s dive in and find your peace of mind!",
    "report_header": "Worry is like a background app running on your phone it quietly drains your battery, slows your focus, and keeps you from enjoying the moment. It’s that what-if loop that turns small pebbles into mountains, affecting everything from your sleep to your confidence.\n\nThe good news? You can hit the refresh button. This assessment is designed to help you spot those mental loops and trade restless thoughts for total clarity. It’s not just a test; it’s your personal toolkit for a lighter, calmer mind.\n\nReady to silence the noise and reclaim your energy? Let’s dive in and find your peace of mind!"
  },
  "1774419076074": {
    "name": "Relationship Challenges",
    "start_instructions": "The person you choose to walk through life with isn’t just a partner they are the co-author of your story. A romantic relationship is a powerful engine that shapes your health, your mindset, and your daily joy. From the way you handle stress to the way you chase your biggest dreams, your other half influences the very rhythm of your life.\n\nThis test is a meaningful tool for reflecting on that rhythm, helping you evaluate the strength of your connection and the health of your shared journey. By looking honestly at your dynamic, you gain the clarity needed to nurture a bond that truly empowers you both. This insight serves as a compass, guiding you toward deeper understanding and a more resilient, fulfilling partnership.",
    "report_header": "The person you choose to walk through life with isn’t just a partner they are the co-author of your story. A romantic relationship is a powerful engine that shapes your health, your mindset, and your daily joy. From the way you handle stress to the way you chase your biggest dreams, your other half influences the very rhythm of your life.\n\nThis test is a meaningful tool for reflecting on that rhythm, helping you evaluate the strength of your connection and the health of your shared journey. By looking honestly at your dynamic, you gain the clarity needed to nurture a bond that truly empowers you both. This insight serves as a compass, guiding you toward deeper understanding and a more resilient, fulfilling partnership."
  },
  "1774419113984": {
    "name": "Self Esteem",
    "start_instructions": "Self-esteem is the internal reputation you have with yourself. It is the overall opinion you hold about your own worth, abilities, and value. Think of it as the foundation of your mental home it shapes how you view your successes and how you bounce back from challenges.\n\nHigh self-esteem acts like a confidence shield, empowering you to try new things and set healthy boundaries. When it’s lower, life can feel a bit more heavy or uncertain. The great news? Self-esteem isn't fixed; it’s a skill you can grow!\n\nThis assessment is an exciting first step in mapping out your inner strengths. There are no right or wrong answers just a wonderful opportunity to see yourself more clearly and unlock your true potential.",
    "report_header": "Self-esteem is the internal reputation you have with yourself. It is the overall opinion you hold about your own worth, abilities, and value. Think of it as the foundation of your mental home it shapes how you view your successes and how you bounce back from challenges.\n\nHigh self-esteem acts like a confidence shield, empowering you to try new things and set healthy boundaries. When it’s lower, life can feel a bit more heavy or uncertain. The great news? Self-esteem isn't fixed; it’s a skill you can grow!\n\nThis assessment is an exciting first step in mapping out your inner strengths. There are no right or wrong answers just a wonderful opportunity to see yourself more clearly and unlock your true potential."
  },
  "1774419168278": {
    "name": "Feeling Low",
    "start_instructions": "Understanding your current emotional landscape is the first step toward personal growth. This assessment is designed to capture a snapshot of your recent mood through various scenarios. Please answer honestly based on how you feel right now; there are no wrong answers, only insights into your unique psychological well-being.",
    "report_header": "Understanding your current emotional landscape is the first step toward personal growth. This assessment is designed to capture a snapshot of your recent mood through various scenarios. Please answer honestly based on how you feel right now; there are no wrong answers, only insights into your unique psychological well-being."
  },
  "1774437549846": {
    "name": "Body Image",
    "start_instructions": "Body image is the subjective mental picture you have of your physical self, encompassing your thoughts, feelings, and perceptions about your body's shape, size, and appearance. It is rarely a literal reflection in the mirror; instead, it is a complex internal dialogue influenced by personal experiences, social standards, and self-esteem.\n\nWhen your body image is positive, it fosters confidence and resilience. However, a negative body image can deeply impact your quality of life, leading to social withdrawal, chronic anxiety, and a diminished sense of self-worth. This assessment is designed to help you explore your current relationship with your body. Please answer honestly, keeping in mind that there are no wrong answers. This is a courageous step toward understanding your inner narrative and moving toward a place of self-acceptance and peace.",
    "report_header": "Body image is the subjective mental picture you have of your physical self, encompassing your thoughts, feelings, and perceptions about your body's shape, size, and appearance. It is rarely a literal reflection in the mirror; instead, it is a complex internal dialogue influenced by personal experiences, social standards, and self-esteem.\n\nWhen your body image is positive, it fosters confidence and resilience. However, a negative body image can deeply impact your quality of life, leading to social withdrawal, chronic anxiety, and a diminished sense of self-worth. This assessment is designed to help you explore your current relationship with your body. Please answer honestly, keeping in mind that there are no wrong answers. This is a courageous step toward understanding your inner narrative and moving toward a place of self-acceptance and peace."
  },
  "1774437605823": {
    "name": "Work Life Balance",
    "start_instructions": "Work-life balance is the effective prioritization between professional obligations and personal life, ensuring that neither sphere consistently overwhelms the other. It is not necessarily a perfect 50/50 split, but rather a fluid state of equilibrium where you have the time and energy to succeed at work while fully engaging in your relationships, health, and hobbies.\n\nWhen this balance is disrupted, the impact is significant: chronic stress, physical exhaustion, and burnout can erode your mental health and professional performance. Conversely, a healthy balance fosters higher productivity, improved mood, and long-term resilience. This assessment is designed to help you gauge your current harmony between these two worlds. Please answer honestly, remembering there are no wrong answers; this is simply a tool to help you identify where you can reclaim your time and well-being.",
    "report_header": "Work-life balance is the effective prioritization between professional obligations and personal life, ensuring that neither sphere consistently overwhelms the other. It is not necessarily a perfect 50/50 split, but rather a fluid state of equilibrium where you have the time and energy to succeed at work while fully engaging in your relationships, health, and hobbies.\n\nWhen this balance is disrupted, the impact is significant: chronic stress, physical exhaustion, and burnout can erode your mental health and professional performance. Conversely, a healthy balance fosters higher productivity, improved mood, and long-term resilience. This assessment is designed to help you gauge your current harmony between these two worlds. Please answer honestly, remembering there are no wrong answers; this is simply a tool to help you identify where you can reclaim your time and well-being."
  },
  "1774437638948": {
    "name": "Motivation",
    "start_instructions": "Motivation is the spark that drives every action we take, from waking up in the morning to chasing our biggest dreams. It is the internal engine that gives us the energy and direction needed to achieve our goals.\n\nWhen motivation is high, it acts as a superpower, boosting our productivity, confidence, and overall happiness. However, when it's low or misplaced, it can lead to procrastination or feeling stuck. Understanding your unique motivational style is the first step toward unlocking your full potential!",
    "report_header": "Motivation is the spark that drives every action we take, from waking up in the morning to chasing our biggest dreams. It is the internal engine that gives us the energy and direction needed to achieve our goals.\n\nWhen motivation is high, it acts as a superpower, boosting our productivity, confidence, and overall happiness. However, when it's low or misplaced, it can lead to procrastination or feeling stuck. Understanding your unique motivational style is the first step toward unlocking your full potential!"
  },
  "1774437671084": {
    "name": "Loss in Life",
    "start_instructions": "Loss in life is a deeply personal and unique journey, and understanding your experience is a vital step toward healing and self-compassion. This assessment is designed to help you reflect on your current emotional landscape and identify the ways grief is impacting your daily life. Please remember that there are no wrong answers; your feelings are a valid reflection of your own path. We encourage you to answer as honestly as possible, allowing this tool to provide a clear and supportive snapshot of where you are today.",
    "report_header": "Loss in life is a deeply personal and unique journey, and understanding your experience is a vital step toward healing and self-compassion. This assessment is designed to help you reflect on your current emotional landscape and identify the ways grief is impacting your daily life. Please remember that there are no wrong answers; your feelings are a valid reflection of your own path. We encourage you to answer as honestly as possible, allowing this tool to provide a clear and supportive snapshot of where you are today."
  },
  "1774437703627": {
    "name": "Exam Anxiety",
    "start_instructions": "Exam anxiety is a common experience that can affect how you feel, think, and perform during assessments. This tool is designed to help you gain a clearer understanding of your unique relationship with test-taking stress and how it may be showing up for you. As you move through the questions, please keep in mind that there are no wrong answers; every response is a valid reflection of your personal experience. By answering honestly, you are taking a helpful step toward recognizing your needs and finding the best strategies to support your academic well-being.",
    "report_header": "Exam anxiety is a common experience that can affect how you feel, think, and perform during assessments. This tool is designed to help you gain a clearer understanding of your unique relationship with test-taking stress and how it may be showing up for you. As you move through the questions, please keep in mind that there are no wrong answers; every response is a valid reflection of your personal experience. By answering honestly, you are taking a helpful step toward recognizing your needs and finding the best strategies to support your academic well-being."
  },
  "1774437722865": {
    "name": "Happiness",
    "start_instructions": "Understanding your current level of happiness is a valuable way to check in with yourself and identify what brings you a sense of fulfillment. This assessment is designed to help you explore your general sense of well-being and how satisfied you feel with various aspects of your daily life. Please remember that there are no wrong answers; happiness is a personal experience that looks different for everyone. By responding honestly based on how you feel right now, you are creating an authentic snapshot of your journey, which can serve as a helpful guide for your personal growth and continued well-being.",
    "report_header": "Understanding your current level of happiness is a valuable way to check in with yourself and identify what brings you a sense of fulfillment. This assessment is designed to help you explore your general sense of well-being and how satisfied you feel with various aspects of your daily life. Please remember that there are no wrong answers; happiness is a personal experience that looks different for everyone. By responding honestly based on how you feel right now, you are creating an authentic snapshot of your journey, which can serve as a helpful guide for your personal growth and continued well-being."
  },
  "1774437743053": {
    "name": "Life Satisfaction",
    "start_instructions": "Life satisfaction is a broad reflection of how you feel about the direction and quality of your journey so far. This assessment provides you with a dedicated space to pause and evaluate the various areas of your world, from your personal achievements to your daily sense of purpose. As you reflect on each question, please remember that there are no wrong answers; your perspective is entirely your own and serves as the most accurate measure of your unique experience. By answering with complete honesty, you are creating a meaningful foundation to better understand your needs and celebrate your progress.",
    "report_header": "Life satisfaction is a broad reflection of how you feel about the direction and quality of your journey so far. This assessment provides you with a dedicated space to pause and evaluate the various areas of your world, from your personal achievements to your daily sense of purpose. As you reflect on each question, please remember that there are no wrong answers; your perspective is entirely your own and serves as the most accurate measure of your unique experience. By answering with complete honesty, you are creating a meaningful foundation to better understand your needs and celebrate your progress."
  },
  "1774437757441": {
    "name": "Trauma",
    "start_instructions": "Reflecting on how a traumatic event has impacted your life is a significant step toward understanding your own resilience and healing process. This assessment is designed to provide you with a safe space to explore your current emotional and physical responses to your experiences. As you navigate these questions, please keep in mind that there are no wrong answers; your feelings and reactions are valid reflections of what you have been through. By answering as honestly as possible, you can gain a clearer perspective on your needs and identify the most supportive path forward for your well-being.",
    "report_header": "Reflecting on how a traumatic event has impacted your life is a significant step toward understanding your own resilience and healing process. This assessment is designed to provide you with a safe space to explore your current emotional and physical responses to your experiences. As you navigate these questions, please keep in mind that there are no wrong answers; your feelings and reactions are valid reflections of what you have been through. By answering as honestly as possible, you can gain a clearer perspective on your needs and identify the most supportive path forward for your well-being."
  },
  "1774437779970": {
    "name": "Managing Emotions",
    "start_instructions": "Managing your emotions is a vital skill that influences how you navigate challenges, build relationships, and maintain your overall well-being. This assessment is designed to help you reflect on how you currently process and respond to your feelings in various situations. As you work through the questions, please remember that there are no wrong answers; your responses are simply a reflection of your unique personal style and current emotional habits. By answering honestly, you can gain valuable insight into your strengths and identify areas where you might want to develop even greater resilience and balance.",
    "report_header": "Managing your emotions is a vital skill that influences how you navigate challenges, build relationships, and maintain your overall well-being. This assessment is designed to help you reflect on how you currently process and respond to your feelings in various situations. As you work through the questions, please remember that there are no wrong answers; your responses are simply a reflection of your unique personal style and current emotional habits. By answering honestly, you can gain valuable insight into your strengths and identify areas where you might want to develop even greater resilience and balance."
  },
  "1775572752740": {
    "name": "DASS 21",
    "start_instructions": "Mental well-being is a dynamic balance, influenced by the unique ways we process the world around us. This assessment is designed to help you explore three key pillars of emotional health: Depression, Anxiety, and Stress. While these experiences often overlap, they represent different ways our system responds to internal and external pressures.\n\nDepression often relates to our mood and energy, affecting how we perceive our value and the future.\n\nAnxiety typically involves our body's alarm system, focusing on apprehension or physical tension regarding what is to come.\n\nStress is the immediate feeling of being overwhelmed or taxed by the demands placed upon us.\n\nUnderstanding where you sit on these scales is a profound act of self-care. This test provides a snapshot of your current emotional landscape, offering clarity that can lead to better coping strategies and a more resilient mindset. Please answer each question based on how you have been feeling recently. There are no right or wrong answers—only honest reflections that bring you closer to understanding and supporting your own well-being.",
    "report_header": "Mental well-being is a dynamic balance, influenced by the unique ways we process the world around us. This assessment is designed to help you explore three key pillars of emotional health: Depression, Anxiety, and Stress. While these experiences often overlap, they represent different ways our system responds to internal and external pressures.\n\nDepression often relates to our mood and energy, affecting how we perceive our value and the future.\n\nAnxiety typically involves our body's alarm system, focusing on apprehension or physical tension regarding what is to come.\n\nStress is the immediate feeling of being overwhelmed or taxed by the demands placed upon us.\n\nUnderstanding where you sit on these scales is a profound act of self-care. This test provides a snapshot of your current emotional landscape, offering clarity that can lead to better coping strategies and a more resilient mindset. Please answer each question based on how you have been feeling recently. There are no right or wrong answers—only honest reflections that bring you closer to understanding and supporting your own well-being."
  },
  "1779169257866": {
    "name": "General Lonliness",
    "start_instructions": "Loneliness is simply the gap between the social connections we have and the ones we want. It’s a common human experience that acts like social hunger, signaling a need for more meaningful bonds.\n\nWhen we listen to this signal, it pushes us toward deeper, more fulfilling friendships. Understanding your patterns is the first step toward building a life of warmth and belonging. This assessment is a supportive way to gain that clarity there are no right or wrong answers, just a path to more connection!",
    "report_header": "Loneliness is simply the gap between the social connections we have and the ones we want. It’s a common human experience that acts like social hunger, signaling a need for more meaningful bonds.\n\nWhen we listen to this signal, it pushes us toward deeper, more fulfilling friendships. Understanding your patterns is the first step toward building a life of warmth and belonging. This assessment is a supportive way to gain that clarity there are no right or wrong answers, just a path to more connection!"
  },
  "1779426087185": {
    "name": "Geriatric Loneliness ",
    "start_instructions": "This scale is designed to help you evaluate your current feelings of social and emotional connection. Please read each statement carefully and select the response that most accurately describes your recent experiences. There are no correct or incorrect answers, and this is not a test of your social skills or worth. Your honest responses will provide the most accurate insight into your well-being, allowing you to better understand your current needs.",
    "report_header": "This scale is designed to help you evaluate your current feelings of social and emotional connection. Please read each statement carefully and select the response that most accurately describes your recent experiences. There are no correct or incorrect answers, and this is not a test of your social skills or worth. Your honest responses will provide the most accurate insight into your well-being, allowing you to better understand your current needs."
  },
  "1779426386879": {
    "name": "Academic Fatigue",
    "start_instructions": "Thank you for taking a moment to check in on your academic well-being. The following questions will help you measure your school-related stress and fatigue levels. Please remember that there are no correct or incorrect answers. This is simply a tool for honest self-reflection. Answer as truthfully as possible based on your current day-to-day routine.",
    "report_header": "Thank you for taking a moment to check in on your academic well-being. The following questions will help you measure your school-related stress and fatigue levels. Please remember that there are no correct or incorrect answers. This is simply a tool for honest self-reflection. Answer as truthfully as possible based on your current day-to-day routine."
  }
};

export function enrichQuizWithInstructions(quiz) {
  if (!quiz) return quiz;
  const entry = quizInstructionsMap[String(quiz.id)] || 
    Object.values(quizInstructionsMap).find(e => e.name && quiz.name && e.name.trim().toLowerCase() === quiz.name.trim().toLowerCase());
  
  if (entry) {
    if (entry.start_instructions) {
      quiz.start_instructions = entry.start_instructions;
    }
    if (entry.report_header) {
      quiz.report_header = entry.report_header;
    }
  }
  return quiz;
}

